language: java

jdk: openjdk8

services:
 - docker

script:  
 - mvn cobertura:cobertura
 
       
after_success:
  - curl --data-binary @codecov.yml https://codecov.io/validate
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dataframe:latest .
  - docker tag dataframe chouaibmo/dataframe:latest
  - docker push chouaibmo/dataframe:latest


