language: java

jdk: openjdk8

services:
 - docker

script:  
 - mvn cobertura:cobertura
 
       
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag dataframe chouaibmo/dataframe:latest
  - docker push chouaibmo/dataframe:latest


